//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContratosMetroplus
{
    using System;
    using System.Collections.Generic;
    
    /*Creo los objetod de la clase Personas*/
    public partial class Personas
    {
        /*Instancio los variables con los metodos GET y SET*/
        public int IdContrato { get; set; }
        public string NumContrato { get; set; }
        public string ModalidadSeleccion { get; set; }
        public string Procedimiento { get; set; }
        public string ClaseContrato { get; set; }
        public string TipoGasto { get; set; }
        public string SectorCorrespondiente { get; set; }
        public string ObjetoContrato { get; set; }
        public decimal ValorInicial { get; set; }
        public int CedulaContratista { get; set; }
        public string NombreCompletoContratista { get; set; }
        public string TipoPersona { get; set; }
        public System.DateTime FechaSuscripcion { get; set; }
        public int CedulaInterventor { get; set; }
        public string NombreCompletoInterventor { get; set; }
        public string TipoVinculacionInterventor { get; set; }
        public string UnidadEjecucion { get; set; }
        public string NumeroUnidadesEjecucion { get; set; }
        public string PactoAnticipo { get; set; }
        public string ValorAnticipo { get; set; }
        public string FiduciaMercantil { get; set; }
        public System.DateTime FechaInicioContrato { get; set; }
        public System.DateTime FechaTerminacionContrato { get; set; }
        public string PublicacionSecop { get; set; }
    }
}
